services:
    php-fpm:
        build: ./docker
        image: phpish:1.2.0
        volumes:
            - ./app:/var/www/html
        networks:
            - mainnet
        depends_on:
            - postgres
            - redis
    nginx:
        image: nginx:1.27-alpine
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - mainnet
        depends_on:
            - php-fpm
    node:
        image: node:20.18.0-alpine
        working_dir: /var/www/html
        user: node
        volumes:
            - ./app:/var/www/html
        environment:
            - NODE_ENV=development
        command: [ 'sleep', 'infinity' ]
        networks:
            - mainnet
    postgres:
        image: postgres:16-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - path: ./app/.env
              required: false
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - mainnet
    redis:
        image: redis:7.4.1-alpine
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379
        networks:
            - mainnet

networks:
    mainnet:


volumes:
    postgres-data:
    redis-data:
