services:
    app:
        build: ./docker
        image: phpish:1.1.0
        volumes:
            - ./app:/var/www/html
        networks:
            - mainnet
        # depends_on:
        # - postgres
    server:
        image: nginx:1.27-alpine
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
        networks:
            - mainnet
        depends_on:
            - app
    # postgres:
    #     image: 'postgres:16-alpine'
    #     volumes:
    #         - postgres-data:/var/lib/postgresql/data
    #     ports:
    #         - '5432:5432'
    #     env_file: ./app/.env
    #     environment:
    #         PGPASSWORD: '${DB_PASSWORD}'
    #         POSTGRES_DB: '${DB_DATABASE}'
    #         POSTGRES_USER: '${DB_USERNAME}'
    #         POSTGRES_PASSWORD: '${DB_PASSWORD}'
    #     networks:
    #         - mainnet

networks:
    mainnet:
# volumes:
#     postgres-data:
