services:
    hub:
        build: .
        image: phpish:1.0.0
        volumes:
            - .:/var/www/html
        networks:
            - mainnet
        depends_on:
            - postgres
    server:
        image: nginx:1.27-alpine
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
            - '443:443'
        networks:
            - mainnet
        depends_on:
            - hub
    postgres:
        image: 'postgres:16-alpine'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        networks:
            - mainnet

networks:
    mainnet:

volumes:
    postgres-data:
