services:
    hub:
        build: .
        container_name: php-fpm
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - mainnet
        depends_on:
            - postgres
    server:
        image: nginx:1.27-alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mainnet
        depends_on:
            - hub
    postgres:
        image: 'postgres:16-alpine'
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - mainnet

networks:
    mainnet:
        driver: bridge

volumes:
    postgres-data:
        driver: local
