services:
    hub:
        build: .
        container_name: php-fpm
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - mainnet
    server:
        image: nginx:1.27-alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mainnet
        depends_on:
            - hub

networks:
    mainnet:
        driver: bridge
